# Resize de imagem

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Carrega a imagem em um tensor
img = tf.io.read_file("dataset\images\images\Alfred_Sisley\Alfred_Sisley_1.jpg")
img = tf.image.decode_jpeg(img, channels=3)

print(img.shape)
print(img)
# Redimensiona a imagem para um tamanho fixo
img = tf.image.resize(img, [733, 1024])
print(img.shape)
print(img)
#tensor to image
# img = tf.image.convert_image_dtype(img, tf.float32)
# img = tf.keras.preprocessing.image.array_to_img(img)
img = tf.image.convert_image_dtype(img, tf.uint8)
img = tf.keras.preprocessing.image.array_to_img(img)



# img = tf.image.convert_image_dtype(img, tf.float32)

# Exibe a imagem
# display.display(PIL.Image.fromarray(img.numpy()))
plt.imshow(img)
plt.show()

(733, 1024, 3)
tf.Tensor(
[[[60 65 61]
  [59 64 60]
  [57 62 58]
  ...
  [74 76 73]
  [72 74 71]
  [74 76 73]]

 [[60 65 61]
  [63 68 64]
  [64 69 65]
  ...
  [80 82 79]
  [82 84 81]
  [86 88 85]]

 [[63 68 64]
  [70 75 71]
  [75 80 76]
  ...
  [86 88 87]
  [90 92 91]
  [97 99 98]]

 ...

 [[32 28 25]
  [38 34 31]
  [42 38 35]
  ...
  [25 17  6]
  [58 48 38]
  [98 88 78]]

 [[31 27 24]
  [38 34 31]
  [44 40 37]
  ...
  [29 21 10]
  [50 40 30]
  [82 72 62]]

 [[31 30 26]
  [38 37 33]
  [44 43 39]
  ...
  [42 33 24]
  [46 37 28]
  [66 57 48]]], shape=(733, 1024, 3), dtype=uint8)
(733, 1024, 3)
tf.Tensor(
[[[60. 65. 61.]
  [59. 64. 60.]
  [57. 62. 58.]
  ...
  [74. 76. 73.]
  [72. 74. 71.]
  [74. 76. 73.]]

 [[60. 65. 61.]
  [63. 68. 64.]
  [64. 69. 65.]
  ...
  [80. 82. 79.]
  [82. 84. 81.]
  [86. 88. 85.]]

 [[63. 68. 64.]
  [70. 75. 71.]
  [75. 80. 76.]
  ...
  [86. 88. 87.]
  [90. 92. 91.]
  [97. 99. 98.]]

 ...

 [[32. 28. 25.]
  [38. 34. 31.]
  [42. 38. 35.]
  ...
  [25. 17.  6.]
  

: 

: 